[project]
name = "team-dh"
version = "0.1.0"
description = "ChatGPT Team redemption code system (Zeabur/Docker-friendly)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "drissionpage>=4.1.1.2",
    "requests>=2.32.5",
    "setuptools>=80.9.0",
    "tomli>=2.3.0",
]
